export const FIRE_PROTECTION_CATEGORIES = [
  'Smoke Detectors',
  'Heat Detectors',
  'Beam Detectors',
  'Manual Call Points',
  'Horn Strobes',
  'Alarm Bells',
  'Speakers',
  'Fire Alarm Control Panels',
  'Annunciators',
  'Modules',
  'Power Supplies',
  'Batteries',
  'Cables',
  'Conduits',
  'Sprinkler Heads',
  'Pipes',
  'Pipe Fittings',
  'Valves',
  'Fire Pumps',
  'Fire Extinguishers',
  'Testing Equipment',
  'Accessories'
] as const;